package com.example.demo.domain;

public enum NotificationDescType {

    CHANGED_STATE, // A changed state to applicant by B
    ASSIGNED_CONTACT, // A assigned to B
    NEW_CONTACT_CREATED, // A created by B
    DOCUMENT_GENERATED, // A facture generated by B
    DOCUMENT_SIGNED, // A zaplatil fakturu
    FACTURE_PAID, // A zaplatil fakturu
    POINTS_APPLICATION, // A wants to applicate points, OZ - B (OZ)
    NEW_CONTACT_REFERAL, // A doporucil noveho kontakta B
    EDR_APPROVED, // B byl schvalen přejit do edr
    DELETED_CONTACT // A odstranil kontakt B
}
