create table campaign_entity
(
    id   int8 not null,
    name varchar(255),
    primary key (id)
);
create table concurrent_fve_entity
(
    id         int8      not null,
    created_at timestamp not null,
    updated_at timestamp,
    due_to     timestamp,
    user_id    int8,
    primary key (id)
);
create table contract_entity
(
    id            int8      not null,
    created_at    timestamp not null,
    updated_at    timestamp,
    contract_type varchar(255),
    lead_id       int8,
    primary key (id)
);
create table edr_link_entity
(
    id                int8 not null,
    registration_link varchar(255),
    current_id        int8,
    primary key (id)
);
create table email_entity
(
    id         int8    not null,
    body       varchar(255),
    email_from varchar(255),
    email_to   varchar(255),
    inbox      boolean not null,
    subject    varchar(255),
    primary key (id)
);
create table facture_entity
(
    id             int8 not null,
    created_at     timestamp,
    due_date       timestamp,
    facture_status varchar(255),
    total_price    numeric(19, 2),
    var_symbol     varchar(255),
    user_id        int8,
    primary key (id)
);
create table facture_item_entity
(
    id         int8 not null,
    name       varchar(255),
    price      numeric(19, 2),
    facture_id int8,
    primary key (id)
);
create table manager_email_entity
(
    id          int8      not null,
    created_at  timestamp not null,
    updated_at  timestamp,
    body        varchar(255),
    contact_id  int8,
    email_from  varchar(255),
    email_to    varchar(255),
    salesman_id int8,
    subject     varchar(255),
    primary key (id)
);
create table referal_entity
(
    id              int8      not null,
    created_at      timestamp not null,
    updated_at      timestamp,
    email           varchar(255),
    name            varchar(255),
    phone           varchar(255),
    referal_link    varchar(255),
    surname         varchar(255),
    link_creator_id int8,
    primary key (id)
);
create table referal_link_entity
(
    id           int8      not null,
    created_at   timestamp not null,
    updated_at   timestamp,
    referal_link varchar(255),
    edr_id       int8,
    primary key (id)
);
create table role_entity
(
    id   int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table salesman_email_entity
(
    id          int8      not null,
    created_at  timestamp not null,
    updated_at  timestamp,
    body        varchar(255),
    contact_id  int8,
    email_from  varchar(255),
    email_to    varchar(255),
    salesman_id int8,
    subject     varchar(255),
    primary key (id)
);
create table user_entity
(
    id                              int8 generated by default as identity,
    accepted_at                     date,
    area                            varchar(255),
    city                            varchar(255),
    concurrent_fve_due_date         boolean not null,
    concurrent_fve_installed        boolean not null,
    concurrent_fve_name             boolean not null,
    confirmation_about_payment_sent boolean not null,
    connected_fve_generated         boolean not null,
    connected_fve_sent              boolean not null,
    connected_fve_signed            boolean not null,
    edr_contract_generated          boolean not null,
    edr_contract_signed             boolean not null,
    email                           varchar(255),
    facture_generated               boolean not null,
    facture_paid                    boolean not null,
    facture_sent                    boolean not null,
    hwsun_monitor_generated         boolean not null,
    hwsun_monitor_sent              boolean not null,
    hwsun_monitor_signed            boolean not null,
    ico                             varchar(255),
    name                            varchar(255),
    op_number                       varchar(255),
    password                        varchar(255),
    phone                           varchar(255),
    request_to_edr_accepted         boolean not null,
    request_to_edr_generated        boolean not null,
    request_to_edr_signed           boolean not null,
    surname                         varchar(255),
    sysel_agreement_generated       boolean not null,
    sysel_agreement_sent            boolean not null,
    sysel_agreement_signed          boolean not null,
    username                        varchar(255),
    wallet_points                   int4,
    campaign_id                     int8,
    referal_id                      int8,
    salesman_id                     int8,
    primary key (id)
);
create table user_entity_roles
(
    user_entity_id int8 not null,
    roles_id       int8 not null,
    primary key (user_entity_id, roles_id)
);
create sequence hibernate_sequence start 1 increment 1;
alter table if exists concurrent_fve_entity
    add constraint FKfvxq73kgul6efk4pfp17n05gc foreign key (user_id) references user_entity;
alter table if exists contract_entity
    add constraint FKcuyb3e9i72ew7qmbw4nd1kmtc foreign key (lead_id) references user_entity;
alter table if exists edr_link_entity
    add constraint FKc9sneoj80ro8rgii8nxmae8n4 foreign key (current_id) references user_entity;
alter table if exists facture_entity
    add constraint FKmeujiqgpdhoiw302t1gvc4u6t foreign key (user_id) references user_entity;
alter table if exists facture_item_entity
    add constraint FK1k27iknftxd3i6jgmyqnt9x0 foreign key (facture_id) references facture_entity;
alter table if exists referal_entity
    add constraint FK368hnpwptj1795lhew3y0l64e foreign key (link_creator_id) references user_entity;
alter table if exists referal_link_entity
    add constraint FKfev7w0g1lxooq772g75ctah8p foreign key (edr_id) references user_entity;
alter table if exists user_entity
    add constraint FK2ao9wegtv8vuxkuhv1qpfebkb foreign key (campaign_id) references campaign_entity;
alter table if exists user_entity
    add constraint FKsp9h5mtbfbuiubs03b8mr1de6 foreign key (salesman_id) references user_entity;
alter table if exists user_entity_roles
    add constraint FKr70hb6wpq5vq5ennenkk12nqk foreign key (roles_id) references role_entity;
alter table if exists user_entity_roles
    add constraint FKjvvinok3stf32dvgie3vr73s0 foreign key (user_entity_id) references user_entity;